name: ASmartApp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.2+2
  intl: ^0.16.1
  sms_autofill: ^1.2.5
  otp_screen: ^0.0.3
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  introduction_screen: ^1.0.9
  http: ^0.12.2
  shared_preferences: ^0.5.10
  imei_plugin: ^1.2.0
  get_mac: ^0.0.1
  connectivity: ^0.4.9+2
  local_auth: ^0.6.3+1
  url_launcher: ^5.7.0
  geolocator: ^6.0.0+4
  google_maps_flutter: ^0.5.32
  flutter_launcher_icons: ^0.8.0
  image_picker: ^0.6.7+11
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1
  cloud_firestore: ^0.14.0
  firebase_database: ^4.1.0
  firebase_storage: ^4.0.0
  firebase_messaging: ^7.0.0
  barcode_scan: ^3.0.1
  fl_chart: ^0.11.1
  intro_slider: ^2.3.3
  sqflite: ^1.3.1+1
  video_player: ^0.10.12
  chewie: ^0.9.4
  youtube_player_flutter: ^7.0.0+7
  flutter_plugin_pdf_viewer: ^1.0.7
  webview_flutter: ^0.3.22+1
  carousel_slider: ^2.3.1
  file_utils: ^0.1.4
  photo_view: ^0.10.2
  table_calendar: ^2.2.3
  google_nav_bar: ^3.0.1
  flutter_jailbreak_detection: ^1.4.0
  dio: ^3.0.10
  cached_network_image: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf
        - asset: fonts/Kanit-Medium.ttf
        - asset: fonts/Kanit-Thin.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
